# FIXED
src/motor.obj: ../src/motor.c
src/motor.obj: C:/StellarisWare/inc/hw_types.h
src/motor.obj: C:/StellarisWare/inc/hw_memmap.h
src/motor.obj: C:/StellarisWare/driverlib/gpio.h
src/motor.obj: C:/StellarisWare/driverlib/pin_map.h
src/motor.obj: C:/StellarisWare/driverlib/sysctl.h
src/motor.obj: C:/StellarisWare/driverlib/pwm.h
src/motor.obj: ../src/init.h
src/motor.obj: ../src/motor.h
